### PR TITLE
Fix bug in bcrypt upgrade path

### LINKED ISSUE #14: I don't believe this gem correctly migrates passwords from bcrypt
It's my understanding from reading the code that when it correctly authenticates a bcrypt password, it migrates it to argon2 by setting [`self.password = hash_argon2_password(unencrypted_password)`](https://github.com/venables/has_secure_password_argon2/blob/master/lib/has_secure_password_argon2.rb#L42) which in turn calls the overridden [`password=`](https://github.com/venables/has_secure_password_argon2/blob/master/lib/has_secure_password_argon2.rb#L64), which again calls `hash_argon2_password()`, thus hashing double-hashing the password and preventing it from authenticating correctly on the next login.

You can verify this by changing this test case to add a second assertion making sure the password authenticates correctly after changing it to argon2:
```ruby
test '#authenticate updates the model for argon2 and returns the model upon valid bcrypt password' do
  password = 'testing'
  bcrypt_hash = BCrypt::Password.create(password)

  model = Model.new(password_digest: bcrypt_hash)
  assert_changes -> { model.password_digest } do
    assert model.authenticate(password)
  end

  assert model.password_digest.start_with?('$argon2')
  assert model.authenticate(password) # NEW ASSERTION
  assert model.persisted?
end
```

This second assertion will fail. This should be fixed, or if this gem is unmaintained as it appears to be, it should be yanked from rubygems to avoid anyone else using it in the future.

### PR DESCRIPTION
**Pull request by venables**
Fixes #14

### CODE REVIEW

File: lib/has_secure_password_argon2.rb [hunk 1]
```diff
@@ -39,7 +39,7 @@ def authenticate(unencrypted_password)
       if password_digest.start_with?('$argon2')
         Argon2::Password.verify_password(unencrypted_password, password_digest, HasSecurePasswordArgon2.secret) && self
       elsif super(unencrypted_password)
-        self.password = hash_argon2_password(unencrypted_password)
+        self.password_digest = hash_argon2_password(unencrypted_password)
```
Comment (swrobel) [inline lib/has_secure_password_argon2.rb]: This seems like the more sensible change to me
```suggestion
        self.password = unencrypted_password
```

**Review by swrobel — CHANGES_REQUESTED** [review]

**Comment by venables** [comment]
Thanks @swrobel !

**Comment by swrobel** [comment]
@venables any plans to release this to Rubygems?
